version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: nastyabirillo/codetracker:1.1
    working_directory: ~/codetracker-data
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            echo | ls /tmp
            echo | ls
            ls /tmp
      - store_artifacts:
          path: htmlcov/
