version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: alyonalyulina/codetracker:1.1
    working_directory: ~/codetracker-data
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            rm src/resources/gumtree/bin/gumtree
            ln -s /opt/gumtree-2.1.2/bin/gumtree src/resources/gumtree/bin/gumtree
            echo | ls
            ./gumtree
            ./gumtree -dm diff 1.py 2.py
            echo | ls /tmp
            python setup.py test
      - store_artifacts:
          path: htmlcov/
