version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image:  nastyabirillo/codetracker:1.3
    working_directory: ~/codetracker-data
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            rm src/resources/gumtree/bin/gumtree
            ln -s /opt/gumtree-2.1.2/bin/gumtree src/resources/gumtree/bin/gumtree
            python setup.py test
      - store_artifacts:
          path: htmlcov/
