version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: nastyabirillo/codetracker:1.1
    working_directory:
      - ~/codetracker-data
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            ls /tmp
            python src/test/solution_space/solution_graph/gumtree_test.py
            ls /tmp
      - store_artifacts:
          path: htmlcov/
