version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: alyonalyulina/codetracker:1.1
    working_directory: ~/codetracker-data
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            echo | ls
            cd src/resources/gumtree/bin/
            echo | ls
            ./gumtree
            ./gumtree -dm diff test_1.py test_2.py
            echo | ls /tmp
      - store_artifacts:
          path: htmlcov/
